"""create proprerties table with geolocation and address

Revision ID: c412283938af
Revises: 8b4f0b17d34c
Create Date: 2026-09-21 15:54:14.294664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c412283938af'
down_revision: Union[str, Sequence[str], None] = '8b4f0b17d34c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('property_type', sa.Enum('HOUSE', 'APARTAMENT', 'FARM', 'COMMERCIAL', name='propertytype', native_enum=False, length=20), nullable=False))
    op.add_column('properties', sa.Column('rental_type', sa.Enum('RESIDENTIAL', 'SEASONAL', 'EVENT', 'SELL', 'ALL', name='rentaltype', native_enum=False, length=20), nullable=False))
    op.add_column('properties', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('properties', sa.Column('price_per_night', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('price_per_month', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('price_selling', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('bedrooms', sa.Integer(), nullable=False))
    op.add_column('properties', sa.Column('bathrooms', sa.Integer(), nullable=False))
    op.add_column('properties', sa.Column('max_guests', sa.Integer(), nullable=False))
    op.add_column('properties', sa.Column('area_sqm', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('state', sa.String(length=2), nullable=False))
    op.add_column('properties', sa.Column('city', sa.String(length=100), nullable=False))
    op.add_column('properties', sa.Column('neighborhood', sa.String(length=100), nullable=False))
    op.add_column('properties', sa.Column('street', sa.String(length=100), nullable=False))
    op.add_column('properties', sa.Column('zip_code', sa.String(length=10), nullable=True))
    op.add_column('properties', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('properties', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column('properties', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_properties_city'), 'properties', ['city'], unique=False)
    op.create_index(op.f('ix_properties_latitude'), 'properties', ['latitude'], unique=False)
    op.create_index(op.f('ix_properties_longitude'), 'properties', ['longitude'], unique=False)
    op.create_foreign_key(None, 'properties', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_index(op.f('ix_properties_longitude'), table_name='properties')
    op.drop_index(op.f('ix_properties_latitude'), table_name='properties')
    op.drop_index(op.f('ix_properties_city'), table_name='properties')
    op.drop_column('properties', 'owner_id')
    op.drop_column('properties', 'longitude')
    op.drop_column('properties', 'latitude')
    op.drop_column('properties', 'zip_code')
    op.drop_column('properties', 'street')
    op.drop_column('properties', 'neighborhood')
    op.drop_column('properties', 'city')
    op.drop_column('properties', 'state')
    op.drop_column('properties', 'area_sqm')
    op.drop_column('properties', 'max_guests')
    op.drop_column('properties', 'bathrooms')
    op.drop_column('properties', 'bedrooms')
    op.drop_column('properties', 'price_selling')
    op.drop_column('properties', 'price_per_month')
    op.drop_column('properties', 'price_per_night')
    op.drop_column('properties', 'is_active')
    op.drop_column('properties', 'rental_type')
    op.drop_column('properties', 'property_type')
    # ### end Alembic commands ###
